general:
  experiment_name: BL_logreg_v1.7_stratified_kfold_С01_min_preprocessing
  seed: 1027309
  num_classes: 2
paths:
  train_csv: data_raw/train.csv
  test_csv: data_raw/test.csv
  trained_models: trained_models
validation:
  enabled: true
  strategy: stratified_kfold
  n_splits: 5
  shuffle: true
  target_column: Survived
  group_by: family
  family:
    surname_column: Name
    sibsp_column: SibSp
    parch_column: Parch
    passenger_id_column: PassengerId
    solo_as_unique_group: true
preprocessing:
  embarked:
    enabled: false
    strategy: most_frequent
  age:
    enabled: true
    strategy: mean_by_title
  initial:
    enabled: true
    output_column: Initial
  age_binning:
    enabled: false
    strategy: equal_width
    output_column: Age_band
    num_bins: 5
    drop_original: true
  categorical_encoding:
    enabled: true
    mapping:
      enabled: true
      columns:
        Sex:
          male: 0
          female: 1
    one_hot:
      enabled: false
      columns:
      - Embarked
      - Initial
      drop_first: false
  family_features:
    enabled: false
    family_size_column: Family_Size
    alone_column: Alone
    drop_original: false
  fare:
    enabled: true
    strategy: median
  fare_binning:
    enabled: false
    strategy: quantile
    output_column: Fare_Range
    num_bins: 4
    drop_original: true
  features:
    given_columns:
    - PassengerId
    - Survived
    - Pclass
    - Name
    - Sex
    - Age
    - SibSp
    - Parch
    - Ticket
    - Fare
    - Cabin
    - Embarked
    use_columns:
    - Pclass
    - Sex
    - Age
    - SibSp
    - Parch
    - Fare
    include_prefixes: []
  save_processed: false
modeling:
  enabled: true
  scale_features: true
  models:
  - name: logistic_regression_no_regularization
    enabled: true
    type: logistic_regression
    params:
      penalty: null
      solver: lbfgs
      max_iter: 5000
  - name: logreg_l1
    enabled: true
    type: logistic_regression
    params:
      penalty: l1
      C: 0.1
      solver: liblinear
      max_iter: 5000
  - name: logreg_l2
    enabled: true
    type: logistic_regression
    params:
      penalty: l2
      C: 0.1
      solver: lbfgs
      max_iter: 5000
  - name: logreg_elasticnet
    enabled: true
    type: logistic_regression
    params:
      penalty: elasticnet
      C: 0.1
      solver: saga
      l1_ratio: 0.5
      max_iter: 5000
metric:
  name: accuracy
inference:
  enabled: true
  model_name: logreg_l2
  use_best_model: true
  id_column: PassengerId
  prediction_column: Survived
  submission_dir: submissions
logging:
  enabled: true
  save_config: true
  save_fold_results: true
  save_summary: true
  save_artifact_paths: true
  save_best_model: true
  save_readable_report: true
training:
  num_epochs: 10
  early_stopping_epochs: 5
  Ir: 0.0001
  mixed_precision: true
  device: cuda
  save_best: true
  save_last: false
  drop_last: true
dataloader_params:
  batch_size: 64
  num_workers: 8
  pin_memory: false
  persistent_workers: true
  shuffle: true
  drop_last: true
loss:
  params: {}
