name: titanic_ml

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
  - pandas
  - scikit-learn
  - joblib
  - omegaconf
  - catboost=1.2.10
  - lightgbm=4.6.0
  - xgboost=3.3.0
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - pip:
    - torch==2.11.0